version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: ntninja/wordpress-postgresql:latest
    container_name: wordpress
    restart: unless-stopped
    #env_file: .env
    environment:
      -  DB_HOST=db:5432
      -  DB_USERNAME=postgres
      -  DB_PASSWORD=password
      -  DB_DATABASE=postgres
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    #  - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  # certbot:
  #   depends_on:
  #       - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #       - ./certbot-etc:/etc/letsencrypt
  #       - ./wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --register-unsafely-without-email --agree-tos --no-eff-email --staging -d araztest.com -d www.araztest.com

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
          driver: bridge                      
